language: scala

env:
  global:
    # BINTRAY_USER
    - secure: "GvJkp/QAYPsN/uGRDJ3+NJFF+80KmGWUPV61IrgMEqAvS47z30xMsD1xgPXWlU85E3TpJSzGlvPFbbaELLvlUvTa0vzVcT0TST98X7h/5ScSH0cGoYcGZAS04J2bgIvFgirYmDi2pSN6lwLd5hT5LL0mQITz5F5iEzTBhLohxfU="
    # BINTRAY_PASS
    - secure: "kclCOLRB7R33ikruTd7vtF6NnT6E27TkMV7RQA+aOgKEpkQM/jkpzSNMzuusYoOB2VStfpaDK4WL+WcrfqhYG08Y17kD3puSiW9KiGWtr3onBdIq9JtlMgmtQWnLbuUobX2oKVuBYpttTgRIwMhAU9hBnQHWSLF3QTZCGfY7wU8="
    - SBT_1_0=1.1.5
    - SBT_1_0_MIN=1.0.0
    - SBT_0_13=0.13.16
    - SBT_0_13_MIN=0.13.9

stages:
  - test
  - publish

jobs:
  include:
    - stage: test
      jdk: openjdk8
      env: SBT_SCRIPTED_VERSION=$SBT_1_0
      script: sbt ^^$SBT_1_0 scripted
    - jdk: openjdk8
      env: SBT_SCRIPTED_VERSION=$SBT_1_0_MIN
      script: sbt ^^$SBT_1_0 scripted
    - jdk: openjdk6
      env: SBT_SCRIPTED_VERSION=$SBT_0_13
      script: sbt ^^$SBT_0_13 scripted
    - jdk: openjdk6
      env: SBT_SCRIPTED_VERSION=$SBT_0_13_MIN
      script: sbt ^^$SBT_0_13 scripted

    - stage: publish
      jdk: openjdk8
      env: SBT_VERSION=$SBT_1_0
      script: echo "Publishing for SBT $SBT_VERSION"
      deploy: &deploy
        - provider: script
          script: sbt ^^$SBT_VERSION publish
          on:
            tags: true
            repo: rtimush/sbt-updates
        - provider: script
          script: sbt ^^$SBT_VERSION publish
          on:
            branch: master
            repo: rtimush/sbt-updates
    - jdk: openjdk6
      env: SBT_VERSION=$SBT_0_13
      script: echo "Publishing for SBT $SBT_VERSION"
      deploy: *deploy

# Use container-based infrastructure
sudo: false

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache/
    - $HOME/.sbt/boot/
