name: CI

on:
  push:
    branches: [ master ]
    tags: [ '*.*.*' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-cache-${{ hashFiles('*.sbt') }}-${{ hashFiles('project/*') }}
      - name: Cache SBT coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-sbt-coursier-cache-${{ hashFiles('*.sbt') }}-${{ hashFiles('project/*') }}

      - uses: olafurpg/setup-scala@v5
        with:
          java-version: zulu@1.8

      - run: sbt scalafmtCheckAll scalafmtSbtCheck test publishLocal
      - uses: actions/upload-artifact@v1
        with:
          name: sbt-updates
          path: /home/runner/.ivy2/local
  scripted:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        include:
          - { sbt: 0_13_9,  java: 8  }
          - { sbt: 0_13_16, java: 8  }
          - { sbt: 1_0_0,   java: 8  }
          - { sbt: 1_3_10,  java: 8  }
          - { sbt: 1_0_0,   java: 11 }
          - { sbt: 1_3_10,  java: 11 }
          - { sbt: 1_3_10,  java: 14 }
      fail-fast: false
    name: test (java ${{ matrix.java }}, sbt ${{ matrix.sbt }})
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-cache-scripted-${{ matrix.sbt }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/*') }}
      - name: Cache SBT coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-sbt-coursier-cache-scripted-${{ matrix.sbt }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/*') }}
      - name: Cache SBT ivy
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-scripted-${{ matrix.sbt }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/*') }}

      - uses: actions/download-artifact@v1
        with:
          name: sbt-updates
          path: /home/runner/.ivy2/local

      - uses: olafurpg/setup-scala@v5
        with:
          java-version: zulu@1.${{ matrix.java }}

      - run: sbt sbt-updates-${{ matrix.sbt }}/scripted
        env:
          CI: true
  test:
    runs-on: ubuntu-latest
    needs: scripted
    steps:
      - run: true
  publish:
    runs-on: ubuntu-latest
    needs: test
    if: github.repository == 'rtimush/sbt-updates' && ( github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') )
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-cache-${{ hashFiles('*.sbt') }}-${{ hashFiles('project/*') }}
      - name: Cache SBT coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-sbt-coursier-cache-${{ hashFiles('*.sbt') }}-${{ hashFiles('project/*') }}

      - uses: olafurpg/setup-scala@v5
        with:
          java-version: zulu@1.8

      - run: sbt publish
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
